# **************************************************************************** #
#                                                           LE - /             #
#                                                               /              #
#    Makefile                                         .::    .:/ .      .::    #
#                                                  +:+:+   +:    +:  +:+:+     #
#    By: manaccac <marvin@le-101.fr>                +:+   +:    +:    +:+      #
#                                                  #+#   #+    #+    #+#       #
#    Created: 2019/10/09 16:05:11 by manaccac     #+#   ##    ##    #+#        #
#    Updated: 2019/12/05 12:50:47 by manaccac    ###    #+. /#+    ###.fr      #
#                                                          /                   #
#                                                         /                    #
# **************************************************************************** #

HEADER		=    libft.h

SRCS		=   ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c \
				ft_isascii.c ft_isdigit.c ft_isprint.c ft_memccpy.c ft_memchr.c \
				ft_memcmp.c ft_memcpy.c ft_memmove.c ft_memset.c ft_strchr.c \
				ft_strdup.c ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_strncmp.c \
				ft_strnstr.c ft_strrchr.c ft_tolower.c ft_toupper.c \
				ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c\
				ft_strmapi.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c \
				ft_putnbr_fd.c ft_putchar.c ft_putstr.c ft_putnbr.c\
				ft_lstnew_bonus.c ft_lstlast_bonus.c ft_lstadd_front_bonus.c \
				ft_lstadd_back_bonus.c ft_lstdelone_bonus.c ft_lstsize_bonus.c \
				ft_lstclear_bonus.c ft_lstiter_bonus.c ft_lstmap_bonus.c \
				ft_putnbr_len.c ft_putstr_len.c ft_putnbr_base.c\
				ft_atoi_base.c ft_print_hex.c ft_putnbr_len_unsigned.c\
				ft_print_p.c ft_taille_hex.c ft_atoi_v2.c ft_nblen.c\
				ft_unsigned_nblen.c ft_putnbr_base_long.c\
				ft_taille_hex_long.c ft_print_pbis.c\

OBJS		=     ${SRCS:.c=.o}

NAME		=     libft.a

RM			=     rm -f

FLAGS		=     -Wall -Wextra -Werror

all:	$(NAME)

%.o: %.c $(HEADER)
	gcc $(FLAGS)  -c $< -o $@

$(NAME):    $(OBJS) $(HEADER)
	ar rcs $(NAME) $(OBJS)

clean:
	$(RM) $(OBJS)

fclean:        clean
	$(RM) $(NAME)

re:            fclean all

.PHONY: clean fclean
